name: CI

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "test/**"
      - "package*.json"
      - "tsconfig.*"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "test/**"
      - "package*.json"
      - "tsconfig.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6.0.10
        with:
          version: 11.22.0
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm ci
      - run: pnpm run build
      - run: pnpm test

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.5.9
      - name: Run Biome
        run: biome ci .
