name: CI

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "test/**"
      - "package*.json"
      - "tsconfig.*"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "test/**"
      - "package*.json"
      - "tsconfig.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: 2.5.9
    - name: Run Biome
      run: biome ci .
